from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    username = models.EmailField(max_length=100,null=True,unique=True)
    firstname = models.CharField(max_length=100,null=True, default = None)
    lastname = models.CharField(max_length=100,null=True, default = None)
    password = models.CharField(max_length=100,null=True, default = None)
    phone = models.CharField(max_length=100,null=True, default = None)
    profileimage = models.FileField(upload_to='media/images/')
    gradyear = models.IntegerField(default = None,null=True)
    posprimary = models.CharField(max_length=100,null=True, default = None)
    possecondary = models.CharField(max_length=100,null=True, default=None)
    instagram = models.CharField(max_length=1000,null=True, default=None)
    twitter = models.CharField(max_length=1000,null=True, default=None)
    facebook = models.CharField(max_length=1000,null=True, default=None)
    school = models.CharField(max_length=100,null=True, default=None)
    city  = models.CharField(max_length=100,null=True, default=None)
    state = models.CharField(max_length=100,null=True, default=None)
    ncaa = models.CharField(max_length=100,null=True, default=None)
    height = models.CharField(max_length=100,null=True, default=None)
    weight = models.CharField(max_length=100,null=True, default=None)
    vertical = models.CharField(max_length=100,null=True, default=None)
    time40 = models.CharField(max_length=100,null=True, default=None)
    gpa = models.CharField(max_length=100,null=True, default=None)
    actscore = models.CharField(max_length=100,null=True, default=None)
    satscore = models.CharField(max_length=100,null=True, default=None)
    classrank = models.CharField(max_length=100,null=True, default=None)
    url1 = models.CharField(max_length=1000,null=True, default=None)
    url2 = models.CharField(max_length=1000,null=True, default=None)
    sbp1 = models.CharField(max_length=1000,null=True, default=None)
    sbp2 = models.CharField(max_length=1000,null=True, default=None)
    sbp3 = models.CharField(max_length=1000,null=True, default=None)
    sbp4 = models.CharField(max_length=1000,null=True, default=None)
    abp1 = models.CharField(max_length=1000,null=True, default=None)
    abp2 = models.CharField(max_length=1000,null=True, default=None)
    abp3 = models.CharField(max_length=1000,null=True, default=None)
    abp4 = models.CharField(max_length=1000,null=True, default=None)
    s1date = models.CharField(max_length=1000,null=True, default=None)
    s1location = models.CharField(max_length=1000,null=True, default=None)
    s1event = models.CharField(max_length=1000,null=True, default=None)
    
    s2date = models.CharField(max_length=1000,null=True, default=None)
    s2location = models.CharField(max_length=1000,null=True, default=None)
    s2event = models.CharField(max_length=1000,null=True, default=None)
    
    s3date = models.CharField(max_length=1000,null=True, default=None)
    s3location = models.CharField(max_length=1000,null=True, default=None)
    s3event = models.CharField(max_length=1000,null=True, default=None)
    coachmessage = models.CharField(max_length=1000,null=True, default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    